services:
  backend:
    build:
      context: ./Backend/MyLibBackend
      dockerfile: Dockerfile
    container_name: mylib-backend
    hostname: backend
    image: ghcr.io/cp-thro/thro-sqs-mylib/backend:latest
    env_file:
      - .env-backend
    environment:
      - MACHINE=prod
      - POSTGRES_USER=backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  frontend:
    image: ghcr.io/cp-thro/thro-sqs-mylib/frontend:latest
    container_name: mylib-frontend
    build:
      context: ./Frontend/mylibfrontend
      dockerfile: Dockerfile
    hostname: frontend
    restart: always
    env_file:
      - .env-frontend
    ports:
      - "5174:80"
    depends_on:
      - postgres-db
      - backend
  postgres-db:
    image: postgres:latest
    container_name: mylib-postgres-db
    hostname: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=backend
    env_file:
      - .env-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
